name: Create PAYDAY mod release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive Mod
      run: |
         .\.github\7za.exe -tzip a ".\completion_tracker_1.0.0.zip" ".\CompletionTracker"
      shell: powershell
    - name: Hash mod and create mod meta file
      id: create_meta_file
      run: |
         $(cat .\.github\meta.json).Replace("%HASH%", $(./.github/hash.exe "./SampleMod").Substring(17)) > ./meta.json
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          This release zip is automatically updated on every push. You can ignore the "x commits behind" message.
        files: |
          ./completion_tracker_1.0.0.zip
          ./meta.json